# The path to a folder of geojson grid files in the wgs84 CRS. 
grid_dir: UPDATEME
# The path to a folder where you want to save the data. 
# During the download process, data will be saved to folders 
# following the convention: `save_dir/YEAR/MONTH/GRID_ID`
save_dir: UPDATEME
# The path to a folder where you process the surface reflectance 
# and UDM data with a Neural Network. 
# e.g. `Y:\planet\stateMap\processing`
processing_dir: UPDATEME
